# Generated by Django 3.1 on 2021-08-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210810_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desctiption',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
