# Generated by Django 3.1 on 2021-08-26 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productgalary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductGalary',
            new_name='ProductGallery',
        ),
    ]
