# Generated by Django 3.1 on 2021-08-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_numnber',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
