# Generated by Django 3.1 on 2021-08-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210816_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
